[versions]
kotlin = "2.3.20"

resourceFactory = "1.3.1"
runTask = "3.0.2"
shadow = "9.4.1"

minotaur = "2.9.0"

[libraries]
kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

[plugins]
resourceFactory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
runTask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }